chattyandmeet/chattyandmeet/urls.py
from django.contrib import admin
from django.urls import path

#urlpatterns = [
#    path('admin/', admin.site.urls),
#]
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

from .views import  search_user,musidebar
urlpatterns = [
    path('search-user/', search_user,name="search-user"),
    path('sider/', musidebar,name="musidebar"),
    path('admin/', admin.site.urls),
    path('', user_views.init, name='init'),
    path('login/', user_views.login_view, name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
        name='password_reset'),
    path('password-reset-done/',
        auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('home/', include('users.urls')),
    path('home/messaging/', include('messaging.urls')),
]

chattyandmeet/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='users-home'),
    path('notifications/',views.notifications,name='users-notifications'),
    path('profile/',views.my_profile_view,name='users-profile'),
    path('profile-update/',views.update_profile,name='users-profile-update'),
    path('profile/<int:id>/',views.others_profile_view,name='other-users-profile'),
    path('search-results/',views.search_results_users,name='search-results-users'),
    path('search-results/keyword=<str:search_text>/',views.search_results_users,name='search-results-users'),
    path('friends/',views.view_all_friends,name='view-all-friends'),
    path('blocked-users-list/',views.blocked_users_list,name='users-blocked-list'),
    path('delete-user/',views.delete_user,name='delete-user'),
    path('ajax/unseen-notifications/',views.unseen_notifications,name='users-notifications-unseen'),
    path('ajax/search-users/',views.search_users,name='search-users-ajax'),
    path('ajax/profile-picture-update/',views.update_profile_picture,name='users-profile-picture-update'),
    path('ajax/search-friends/',views.search_friends,name='search-friends-ajax'),
    path('ajax/change-friends/',views.change_friends,name='change-friends-ajax'),
    path('ajax/block-user/<int:id>/<str:action>/',views.block_users,name='block-users'),
]

chattyandmeet/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.utils import timezone
from datetime import date
from .validators import validate_dob
from django.core.cache import cache
import datetime
from chattyandmeet import settings
from uuid import uuid4


class Profile(models.Model):
	def dp_rename_and_path(instance, filename):
	    extension = filename.split('.')[-1]
	    time_stamp = timezone.now()
	    time_stamp = time_stamp.strftime("%d-%m-%Y_%I-%M-%S%p")
	    path = 'profile_pics/{username}/{time_stamp}_{randomstring}.{extension}'.format(
	    	username = instance.user.username,
	    	time_stamp = time_stamp,
	    	randomstring = uuid4().hex,
	    	extension = extension,
	    )
	    print(path)
	    return path

	SEX_CHOICES = [
		('m','Male'),
		('f','Female'),
		('o','Others'),
	]

	dob_default = date.today()
	dob_default = dob_default.replace(year = dob_default.year-5)
	user=models.OneToOneField(User,on_delete = models.CASCADE)
	display_picture=models.ImageField(default = 'profile_pics/default.jpg', upload_to = dp_rename_and_path)
	first_name=models.CharField(max_length = 20)
	last_name=models.CharField(max_length = 20)
	sex = models.CharField(max_length = 1, choices = SEX_CHOICES, default = 'm')
	dob=models.DateField(default=dob_default, validators = [validate_dob], verbose_name='Date of Birth')
	bio=models.TextField(max_length = 100, default = "Hi there! Let's be friends")

	def __str__(self):
		return f"{self.user.username}'s Profile"

	def save(self,*args,**kwargs):
		super(Profile,self).save(*args,**kwargs)

		img=Image.open(self.display_picture.path)
		print('andar hu bsdk')
		if img.height>300 or img.width>300:
			output_size=(300,300)
			img.thumbnail(output_size)
			img.save(self.display_picture.path)


class Address(models.Model):
    profile=models.OneToOneField(Profile,on_delete=models.CASCADE)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=30)
    country = models.CharField(max_length=50)

    class Meta:
    	verbose_name = 'Address'
    	verbose_name_plural = 'Address'

    def __str__(self):
    	return f"{self.profile.user.username}'s Address"


class Friends(models.Model):
	current_user = models.OneToOneField(User, related_name='owner', on_delete=models.CASCADE)
	friends = models.ManyToManyField(User, related_name='friends', blank=True)
	pending_sent_list = models.ManyToManyField(User, related_name='pending_sent_list', blank=True)
	pending_received_list = models.ManyToManyField(User, related_name='pending_received_list', blank=True)

	class Meta:
		verbose_name = 'Friends'
		verbose_name_plural = 'Friends'

	def __str__(self):
		return f"{self.current_user}'s friends"

	@classmethod
	def add_friend(cls, to_user, from_user):
		from_user_friendlist = cls.objects.get(current_user = from_user)
		to_user_friendlist = cls.objects.get(current_user = to_user)
		from_user_friendlist.pending_sent_list.add(to_user)
		to_user_friendlist.pending_received_list.add(from_user)

	@classmethod
	def remove_friend(cls, friend_user, from_user):
		from_user_friendlist = cls.objects.get(current_user = from_user)
		friend_user_friendlist = cls.objects.get(current_user = friend_user)
		from_user_friendlist.friends.remove(friend_user)
		friend_user_friendlist.friends.remove(from_user)

	@classmethod
	def cancel_sent_request(cls, to_user, from_user):
		from_user_friendlist = cls.objects.get(current_user = from_user)
		to_user_friendlist = cls.objects.get(current_user = to_user)
		from_user_friendlist.pending_sent_list.remove(to_user)
		to_user_friendlist.pending_received_list.remove(from_user)

	@classmethod
	def handle_received_request(cls, to_user, from_user, choice):
		from_user_friendlist = cls.objects.get(current_user = from_user)
		to_user_friendlist = cls.objects.get(current_user = to_user)
		if choice == 'accept':
			from_user_friendlist.friends.add(to_user)
			to_user_friendlist.friends.add(from_user)
			from_user_friendlist.pending_received_list.remove(to_user)
			to_user_friendlist.pending_sent_list.remove(from_user)

		elif choice == 'decline':
			from_user_friendlist.pending_received_list.remove(to_user)
			to_user_friendlist.pending_sent_list.remove(from_user)


class BlockedUsers(models.Model):
	user = models.OneToOneField(User, related_name='me', on_delete=models.CASCADE)
	blocked_list = models.ManyToManyField(User, related_name='is_blocked_by', blank=True)

	class Meta:
		verbose_name = 'Blocked Users'
		verbose_name_plural = 'Blocked Users'

	def __str__(self):
		return f"{self.user}'s blocked list"

	@classmethod
	def block_user(cls, user, user_to_be_blocked):
		f1 = Friends.objects.get(current_user=user)
		f2 = Friends.objects.get(current_user=user_to_be_blocked)
		f1.pending_sent_list.remove(user_to_be_blocked)
		f1.pending_received_list.remove(user_to_be_blocked)
		f1.friends.remove(user_to_be_blocked)
		f2.pending_sent_list.remove(user)
		f2.pending_received_list.remove(user)
		f2.friends.remove(user)
		obj = cls.objects.get(user=user)
		obj.blocked_list.add(user_to_be_blocked)

	@classmethod
	def unblock_user(cls, user, blocked_user):
		obj = cls.objects.get(user=user)
		obj.blocked_list.remove(blocked_user)


class Notifications(models.Model):
	TYPE_CHOICES = [
		('sent', 'sent you a friend request'),
		('accepted', 'accepted your friend request'),
	]

	to_user = models.ForeignKey(User, related_name='my_notifications', on_delete=models.CASCADE)
	type = models.CharField(max_length = 10, choices = TYPE_CHOICES, default = 'sent')
	seen = models.BooleanField(default = False)
	time_stamp = models.DateTimeField(default=timezone.now)
	from_user = models.ForeignKey(User, related_name='about_whom', on_delete=models.CASCADE)

	class Meta:
		verbose_name = 'Notifications'
		verbose_name_plural = 'Notifications'

	def __str__(self):
		time_stamp = self.time_stamp.strftime("%a-%b/%d/%Y-%I:%M:%S %p %Z")
		return f"ID: {self.id} | {self.to_user}'s notification at {time_stamp}"

	@classmethod
	def add_notification(cls, to_user, type, from_user):
		n = cls.objects.filter( to_user=to_user,
								from_user = from_user
								)
		print(n.count())
		if n.count()>20:
			n.first().delete()
		n = cls.objects.create(	to_user=to_user,
								type = type,
								from_user = from_user
								)
		n.save()

	@classmethod
	def delete_notification(cls, to_user, type, from_user):
		try:
			n = cls.objects.get(to_user=to_user,
								type = type,
								from_user = from_user
								)
		except:
			n = cls.objects.none()
		n.delete()

chattyandmeet/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile,Address
from .validators import validate_dob


class UserRegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username','email','password1','password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['email']


class ProfileCreateForm(forms.ModelForm):
	dob = forms.DateField(validators = [validate_dob], label='Date of Birth')

	class Meta:
		model = Profile
		fields = ['first_name', 'last_name', 'sex', 'dob', 'bio']


class AddressForm(forms.ModelForm):
	
	class Meta:
		model = Address
		fields = ['city','state','country']


class ProfileUpdateForm(forms.ModelForm):
	
	class Meta:
		model = Profile
		fields = ['sex', 'bio']


class ProfilePictureForm(forms.ModelForm):
	display_picture = forms.ImageField(label='')

	class Meta:
		model = Profile
		fields = ['display_picture']

chattyandmeet/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>

	<title>meetandchat</title>
	<meta charset="utf-8">
	<meta name="description" content="A secure chatting application to connect with your friends">
  	<meta name="keywords" content="chatting, social, media, friends, secure, encryption">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.js"></script>
    <script src="{% static 'users/js/ajax.js' %}"></script>
    <script src="{% static 'messaging/js/ajax.js' %}"></script>
    <script src="{% static 'messaging/js/general.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script >
    	new WOW().init();
    </script>
    <link rel="icon" href="{% static 'users/images/favik.jpg' %}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.2/emojionearea.min.css">
	<link rel="stylesheet" href="{% static 'users/css/my_css.css' %}">
	<style>
	    body{
    background-image: url("static/sea.gif");
     background-repeat: no-repeat;
  background-size: 100% 200%;
  height: 120px;
  /*position: relative;*/
}

.pl{
color:grren;
}
	</style>
</head>

<body data-user-status="{{ user.is_authenticated }}">

	{% if user.is_authenticated %}


		<nav class="navbar navbar-expand-sm  navbar-light" style="background:#1af">
	  		<a href="{% url 'users-home' %}" class="navbar-brand">
				<img src="{% static 'users/images/gh.jpg' %}" alt="Meetandchat" id="logo" class="img-thumbnail" height="100" width="100">
			<small style="color:gold"> Tn-media </small>

			</a>


			{% if user.profile.display_picture%}
            <a href="{% url 'musidebar' %}" >
                <img src="{{ user.profile.display_picture.url }}" alt="Display Picture" style="border-radius:50%" height="100" width="100">
            <small class="badge badge-primary">
                {{user.username}}
            </small>
            </a>

			{% else %}
			<a href="{% url 'musidebar'%}" >
            <img src="{%  static 'avatar-bg.jpg' %}" alt="Display Picture" class="img-thumbnail dp" height="100" width="100">
            <small class="badge badge-primary">
                {{user.username}}
            </small>
            </a>
			{% endif %}

		  	<form class="form-inline pl-3 pr-2">
		  		<div class="input-group">
			  		<input type="search" class="form-control" id="search-users" autocomplete="off" placeholder="Search users here" data-ajax-url="{% url 'search-users-ajax' %}">
		  			<div class="input-group-append">
				  		<span class="input-group-text fas fa-user-plus"></span>
				  	</div>
		  		</div>
		  	</form>

		    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links" aria-controls="navbar-links" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		    <div class="collapse navbar-collapse" id="navbar-links">
				<div class="col-sm my-3">
					<div class="text-dark">
						<span class="badge">
							<i id="notification-icon" class="fa fa-bell fa-2x" data-ajax-url="{% url 'users-notifications-unseen'%}"></i>
						</span>
						<div id="notification-count" data-ajax-url="{% url 'users-notifications' %}">
				  		</div>
					</div>
					<div id="notification-body" class="dropdown-menu bg-light" data-ajax-url="{% url 'users-notifications' %}">
				  	</div>
			    </div>
				<ul id="navbar-list" class="navbar-nav">
			    	{% if request.user.profile.first_name %}
				    	<li class="nav-item ml-2">
							<a id="home-url" class="nav-link" href="{% url 'users-home' %}">
							    <i class="fa fa-home">

							    </i>
							</a>
						</li>
					{% endif %}
			    	<li class="nav-item ml-2">
						<a class="nav-link" href="{% url 'users-profile' %}">Profile</a>
					</li>
					{% if request.user.friends.exists %}
						<li class="nav-item ml-2">
							<a id="friends-url" class="nav-link" href="{% url 'view-all-friends' %}">Friends</a>
						</li>
					{% endif %}
				    <li class="nav-item dropdown ml-2">
						<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
						    <i class="fa fa-cog">

						    </i>
						</a>
						<div id="settings" class="dropdown-menu">
							<a href="{% url 'users-blocked-list' %}" class="dropdown-item">Blocked users</a>
							<div class="dropdown-divider"></div>
							<a href="{% url 'password_reset' %}" class="dropdown-item">Change password</a>
							<div class="dropdown-divider"></div>
					        <a href="#" id="delete-account" class="dropdown-item" data-toggle="modal"data-target="#deleteModal">Delete account</a>
						</div>
						<div class="modal fade" id="deleteModal">
						    <div class="modal-dialog modal-dialog-centered">
						      	<div class="modal-content">
							        <div class="modal-body">
							        	<div class="row">
								        	<div class="col-sm font-weight-bold">
								        		Are you sure you want to delete your account?<br>
								        		(All your data will be lost permanently)
								        	</div>
								          	<div class="col-sm-1">
									          	<button type="button" class="close" data-dismiss="modal">
									          		&times;
									          	</button>
									        </div>
									    </div>
							        </div>
							        <div class="modal-footer">
							          	<a href="{% url 'delete-user' %}" class="btn btn-danger">
							          		Yes
							         	 </a>
							         	<button type="button" class="btn btn-dark" data-dismiss="modal">
							          		Cancel
							          	</button>
							        </div>
							    </div>
						    </div>
						</div>
				    </li>
				    <li class="nav-item ml-2">
						<a class="nav-link" href="{% url 'logout' %}">
						  logout
						</a>
				    </li>
			  	</ul>
			</div>
		</nav>
		<div id="search-results-users" class="container-fluid">
		</div>
	{% endif %}

	{% if messages %}
		<div id="messages" class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-10 font-weight-bold">
					{% for message in messages %}
						{% load tags %}
						<div class="alert alert-{{ message.tags|get_tag }} alert-dismissible text-center">
							{{ message }}
							<a href="#" class="close" data-dismiss="alert" aria-label="close">
								&times;
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	{% endif %}

	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>

</body>
</html>

chattyandmeet/users/templates/users/blocked_users.html
{% extends "users/base.html" %}	
{% block content %}

	<div class="container">
		{% if blocked_users.count > 0 %}
			<div class="col-sm text-info my-4">
				<h3>
					Blocked Users: 
				</h3>				
			</div>
			{% for u in blocked_users %}
				<div class="row mt-2">
					<div class="col-sm-6 border border-secondary rounded">
						<div class="row bg-light">
							<div class="col-sm-1 mt-2 mb-1 ml-3">
								<img src="{{ u.profile.display_picture.url }}" alt="Display Picture" class="rounded-circle search-dp">
							</div>
							<div class="col-sm-5 mt-1 ml-4">
								<div class="row font-weight-bold">
									@{{u.username}}
								</div>
								<div class="row">
									{{u.profile.first_name}} {{u.profile.last_name}}
								</div>
							</div>
							<a href="{% url 'other-users-profile' id=u.id %}" class="stretched-link">
							</a>
						</div>
					</div>

					<div class="col-sm-2 my-2 ml-2">
						<button type="button" class="block-button btn btn-dark btn-sm" data-ajax-url="{% url 'block-users' id=u.id action='unblock'%}">
							Unblock User
						</button>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<div class="col-sm text-info mt-4">
				<h3>
					No Blocked Users
				</h3>				
			</div>
		{% endif %}

	</div>

{% endblock content %}

chattyandmeet/users/templates/users/init.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}	
{% block content %}

	<div class="container mt-3">
		<h1 class="font-weight-bold text-center">WELCOME</h1>
		<div class="row justify-content-center">
			<div class="col-sm-5">
				<h4 class="font-weight-bold text-primary mt-3">Sign Up here:</h4>
				<form method="POST" class="form-control-sm">
					<div class="form-group">
						{% csrf_token %}
						{{ form|crispy }}
					</div>
					<div class="row ml-1">
						<button type="submit" class="btn btn-dark btn-sm">Sign Up</button>
						<div class="row small mt-1 ml-3"> 
							<a class="font-weight-bold text-info" href="{% url 'login' %}">
								Already a user? Log In
							</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	
{% endblock content %}

chattyandmeet/users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

	<div class="container mt-3">
		<h1 class="font-weight-bold text-center">WELCOME</h1>
		<div class="row justify-content-center">
			<div class="col-sm-5">
				<form method="POST" id="login">
					<div class="form-group">
						{% csrf_token %}
						{{ form|crispy }}
					</div>
					<div class="row mt-2 ml-1">
						<button type="submit" class="btn btn-dark btn-sm">
							Sign In
						</button>
					</div>
					<div class="small">
						<div class="row ml-1 mt-2">
							<a class="font-weight-bold text-info" href="{% url 'password_reset' %}">Forgot password?
							</a>
						</div>
						<div class="row ml-1">
							<a  class="font-weight-bold text-info" href="{% url 'init' %}">
								New here? Sign Up
							</a>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>


{% endblock content %}

chattyandmeet/users/templates/users/notifications_ajax.html
{% if mode == 'count' %}	
	{% if notifications_count %}
		<span id="notification-count-value" class="badge bg-light border border-light rounded-circle"  data-last="{{ last }}">
  			{{ notifications_count }}
  		</span>
  	{% endif %}

{% elif mode == 'body' %}
	{% if notifications %}
		{% for n in notifications %}
			<a href="{% url 'other-users-profile' id=n.from_user.id %}" class="dropdown-item text-info notification-link">
				<b>@{{ n.from_user.username }}</b> has {{ n.get_type_display }}
			</a>
		{% endfor %}

	{% else %}
		{% for n in all_notifications %}
			<a href="{% url 'other-users-profile' id=n.from_user.id %}" class="dropdown-item text-info notification-link">
				<b>@{{ n.from_user.username }}</b> has {{ n.get_type_display }}
			</a>
		{% endfor %}
	{% endif %}
{% endif %}

chattyandmeet/users/templates/users/profile.html
{% extends "users/base.html" %}	
{% block content %}

	<div class="container mt-3">
		<h4 class="font-weight-bold text-primary mt-3">
			@{{ person.username}}
		</h4>
		<h4 class="font-weight-bold">
			{{ person.profile.first_name }} {{ person.profile.last_name }}
		</h4>

		<div class="row mt-3">
			<div class="col-sm-4">
				<div class="rounded">
					<img src="{{ person.profile.display_picture.url }}" alt="Display Picture" class="img-thumbnail dp">
				</div>
				{% if person == user %}
					<div class="btn-group dropright ml-1 mt-1">
						<button class="btn btn-sm btn-dark dropdown-toggle" data-toggle="dropdown">
							Update Profile Picture
						</button>
						<div class="dropdown-menu bg-light">
							<div class="dropdown-header">
								<form method="post" enctype="multipart/form-data" class="form-control-sm dropdown-header">	
									{% csrf_token %}
									{{ dp_form }}
									<button type="submit" class="btn btn-sm btn-dark" data-ajax-url="{% url 'users-profile-picture-update' %}">
										Upload picture
									</button>
								</form>
							</div>
							<div class="dropdown-divider"></div>
					        <div id="remove-picture" class="dropdown-item ml-4" data-ajax-url="{% url 'users-profile-picture-update' %}">
					        	Remove picture
					        </div>
						</div>
					</div>
				{% endif %}
			</div>

			<div class="col-sm ml-5">
				<div class="col-sm ml-5">
					<h5 class="font-weight-bold font-italic">
						About
					</h5>
					<ul class="list-unstyled p-2 font-weight-normal">
						<li class="mt-1">{{ person.profile.get_sex_display }}</li>
						<li class="mt-1">
							I'm from 
								{{ person.profile.address.city }},
								{{ person.profile.address.state }},
								{{ person.profile.address.country }}
						</li>
						{% if person == user %}
							<li class="mt-1">Born on {{ person.profile.dob|date:"d/m/Y" }}</li>
							<li class="mt-1">My email id is {{ person.email }}</li>
							<li class="font-italic mt-3">User since {{ person.date_joined }}</li>
						{% endif %}
					</ul>
				</div>

				<div class="col-sm-5 mt-5 ml-5">
					<h5 class="font-weight-bold font-italic">
						Bio
					</h5>
					<div id="bio" class="small font-weight-normal border border-secondary shadow bg-light ml-1 p-3">
						{{ person.profile.bio }}
					</div>
				</div>
			</div>

		</div>

		
		{% if person == user %}
		<div class="row mt-5">
			<div class="col-sm mt-2 ml-2">
				<a href="{% url 'users-profile-update' %}" class="btn btn-dark btn-sm w-25">
					Update Profile
				</a>
			</div>
		</div>

		{% else %}
			{% if is_blocked %}
				<div class="row mt-4 ml-1">
					<div class=" col-sm-3">
						<button type="button" class="block-button btn btn-dark btn-sm" data-ajax-url="{% url 'block-users' id=person.id action='unblock'%}">
							Unblock User
						</button>
					</div>
				</div>
			{% else %}
				<div class="row mt-4 ml-1">
					{% csrf_token %}
					{% if is_friend %}
						<div class=" col-sm-3">
							<button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#friendModal">
								Remove Friend
							</button>
							<div class="modal fade" id="friendModal">
							    <div class="modal-dialog modal-dialog-centered">
							      	<div class="modal-content">
								        <div class="modal-body">
								        	<div class="row">
									        	<div class="col-sm">
									        		Are you sure you want to remove <b> @{{ person.username }}</b> from your friends?
									        	</div>
									          	<div class="col-sm-1">
										          	<button type="button" class="close" data-dismiss="modal">
										          		&times;
										          	</button>
										        </div>
										    </div>
								        </div>
								        <div class="modal-footer">
								          	<button id="remove" type="button" class="ajax-friend-button btn btn-dark" data-user-id={{person.id}} data-ajax-url="{% url 'change-friends-ajax' %}">
								          		Yes
								         	 </button>
								         	<button type="button" class="btn btn-danger" data-dismiss="modal">
								          		Cancel
								          	</button>
								        </div>    
								    </div>
							    </div>
							</div>
						</div>
					{% elif sent %}
						<div class="col-sm-3">
							<button id="cancel_request" class="ajax-friend-button btn btn-info btn-sm" data-user-id={{person.id}} data-ajax-url="{% url 'change-friends-ajax' %}">
								Cancel Friend Request
							</button>
						</div>
					{% elif received %}
						<div class="col-sm-2 small text-secondary">
							Respond to request
						</div>
						<div class="col-sm-1">
							<button id="accept" class="ajax-friend-button btn btn-info btn-sm" data-user-id={{person.id}} data-ajax-url="{% url 'change-friends-ajax' %}">
								Accept
							</button>
						</div>
						<div class="col-sm-1">
							<button id="decline" class="ajax-friend-button btn btn-danger btn-sm" data-user-id={{person.id}} data-ajax-url="{% url 'change-friends-ajax' %}">
								Decline
							</button>
						</div>
					{% else %}
						<div class="col-sm-2">
							<button id="add" class="ajax-friend-button btn btn-info btn-sm" data-user-id={{person.id}} data-ajax-url="{% url 'change-friends-ajax' %}">
								Add Friend
							</button>
						</div>
					{% endif %}
				</div>
				<div class="row mt-3 ml-1">
					<div class="col-sm-2">
						{% if not is_blocked %}
							<button type="button" class="block-button btn btn-dark btn-sm" data-ajax-url="{% url 'block-users' id=person.id action='block'%}">
								Block User
							</button>
						{% endif %}
					</div>
				</div>
			{% endif %}
		{% endif %}

	</div>

{% endblock content %}